package com.sfl.mission_service.dto;

import lombok.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AlertDTO {
    private Long alertId;       // optional, if generated by Alert service
    private Long missionId;     // link back to mission
    private Long incidentId;    // link back to incident
    private String status;      // mission status (ASSIGNED, COMPLETED, ESCALATED)
    private String severity;    // severity of incident
    private String location;    // location of incident
    private String message;     // optional alert message
    private String timestamp;   // when alert was created
}
